import type { EarningsAnalysis } from "@/lib/earnings/types";

export function sampleAnalysis(overrides: Partial<EarningsAnalysis> = {}): EarningsAnalysis {
  const generatedAt = overrides.generatedAt ?? "2026-02-01T12:00:00.000Z";
  const analysisId = overrides.analysisId ?? `NVDA-combined-${generatedAt.replace(/[-:.]/g, "").slice(0, 15)}Z`;
  return {
    analysisId,
    ticker: "NVDA",
    language: "en",
    mode: "combined",
    company: { ticker: "NVDA", name: "NVIDIA", sourceIds: ["src-1"] },
    event: {
      id: "evt-nvda-2026q1",
      ticker: "NVDA",
      fiscalPeriod: "Q1 2026",
      fiscalYear: 2026,
      reportDate: "2026-02-01",
      timing: "after_close",
      status: "reported",
      sourceIds: ["src-1"],
    },
    upcomingEvent: null,
    recentEvent: null,
    estimates: { ticker: "NVDA", eventId: "evt-nvda-2026q1", revenueEstimate: 100, epsEstimate: 2, sourceIds: ["src-1"] },
    results: { ticker: "NVDA", eventId: "evt-nvda-2026q1", revenueActual: 110, epsActual: 2.2, sourceIds: ["src-1"] },
    quote: null,
    marketReaction: null,
    financials: [],
    segmentRevenue: [],
    historicalPattern: [],
    historicalSummary: {
      revenueBeatCount: 0,
      epsBeatCount: 0,
      revenueDataPoints: 0,
      epsDataPoints: 0,
      quarters: 0,
      limitedHistory: true,
    },
    news: [],
    filings: [],
    transcript: null,
    analystRevisions: [],
    beatMiss: { revenue: "beat", eps: "beat", guidance: "unavailable" },
    oneLineVerdict: "Revenue and EPS beat estimates.",
    eventStatus: [],
    whatChanged: [],
    keyQuestions: [],
    keyDrivers: ["Datacenter demand remained strong."],
    riskSignals: [],
    qualityOfEarnings: [],
    summaryBullets: ["Revenue and EPS beat estimates."],
    watchNext: [],
    confidence: { label: "medium", reason: "Stored test analysis." },
    caveats: [],
    capabilityStatus: {},
    missing: [],
    issues: [],
    conflicts: [],
    sources: [{ id: "src-1", title: "NVIDIA earnings", retrievedAt: generatedAt }],
    generatedAt,
    demo: true,
    ...overrides,
  };
}
