export const QVERIS_EARNINGS_TOOL_IDS = {
  calendar: "alphavantage.earnings_calendar.list.v1.467a92c0",
  consensusCalendar: "finnhub.calendar.earnings.retrieve.v1.1552775d",
  earningsHistory: "finnhub.stock.earnings.retrieve.v1.dda8afb8",
  earningsDates: "twelvedata.earnings.retrieve.v1.e3dcf5a7",
  indexConstituents: "mcp_gildata.indexconstituentstocks.v1",
  secCompanySubmissions: "sec.company.submissions.v1",
  profile: "finnhub.company.profile.v2.get.v1",
  marketCapBatch: "financialmodelingprep.stable.marketcapitalizationbatch.retrieve.v1.d2caebb9",
  quote: "eodhd.live_v2.us_quote_delayed.retrieve.v1.f0e13d45",
  historicalPrice: "financialmodelingprep.stable.historicalpriceeod.dividendadjusted.retrieve.v1.1e0b27c9",
  news: "qveris_finance.finance_news_aggregation_v1",
  filingsCik: "financialmodelingprep.stable.secfilingscompanysearch.symbol.retrieve.v1.5cf7397d",
  filingsSearch: "financialmodelingprep.stable.secfilingssearch.cik.retrieve.v1.6c73a2ce",
  transcript: "alphavantage.earnings_call_transcript.query.v1.467a92c0",
  incomeStatement: "financialmodelingprep.stable.incomestatement.retrieve.v1.dd6d583f",
  balanceSheet: "financialmodelingprep.stable.balancesheetstatement.retrieve.v1.bce203b1",
  cashFlow: "financialmodelingprep.stable.cashflowstatement.retrieve.v1.dfeb9354",
  revenueSegment: "financialmodelingprep.stable.revenueproductsegmentation.retrieve.v1.8faa287f",
} as const;
